### ISSUE TITLE
install this

### ISSUE THREAD

**Issue by edvalbuena** [onnet/mod_kazoo#6]
Hi, 

I like what you did with the interface. I have a question though, how do you install this? is this like wordpress?

**Comment by onnet** [comment]
Hi,

It needs Zotonic and since Zotonic is also CMS the answer could be 'Yes'.
But in this particular case, Zotonic is used as a framework, therefore  the answer could be also 'No'. :)

Anyway, you can get acquainted with Zotonic, install this module and play with it. 
To get deeper into it and introduce some changes, you'll need some (but not too much) Erlang and Erlydtl knowledge.

Regards,
Kirill
